package co.com.soinsoftware.billing.entity;

// Generated 26-may-2016 15:17:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Configuration generated by hbm2java
 */
public class Configuration implements java.io.Serializable {

	private Integer id;
	private Company company;
	private String name;
	private long from;
	private long to;
	private long current;
	private Date creation;
	private Date updated;
	private boolean enabled;
	private Set receipts = new HashSet(0);
	private Set itemconcepts = new HashSet(0);

	public Configuration() {
	}

	public Configuration(Company company, String name, long from, long to,
			long current, Date creation, Date updated, boolean enabled) {
		this.company = company;
		this.name = name;
		this.from = from;
		this.to = to;
		this.current = current;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Configuration(Company company, String name, long from, long to,
			long current, Date creation, Date updated, boolean enabled,
			Set receipts, Set itemconcepts) {
		this.company = company;
		this.name = name;
		this.from = from;
		this.to = to;
		this.current = current;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
		this.receipts = receipts;
		this.itemconcepts = itemconcepts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getFrom() {
		return this.from;
	}

	public void setFrom(long from) {
		this.from = from;
	}

	public long getTo() {
		return this.to;
	}

	public void setTo(long to) {
		this.to = to;
	}

	public long getCurrent() {
		return this.current;
	}

	public void setCurrent(long current) {
		this.current = current;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getReceipts() {
		return this.receipts;
	}

	public void setReceipts(Set receipts) {
		this.receipts = receipts;
	}

	public Set getItemconcepts() {
		return this.itemconcepts;
	}

	public void setItemconcepts(Set itemconcepts) {
		this.itemconcepts = itemconcepts;
	}

}
