package co.com.soinsoftware.billing.entity;

// Generated 26-may-2016 15:17:44 by Hibernate Tools 4.3.1

/**
 * ItemId generated by hbm2java
 */
public class ItemId implements java.io.Serializable {

	private int idreceipt;
	private int iditemconcept;

	public ItemId() {
	}

	public ItemId(int idreceipt, int iditemconcept) {
		this.idreceipt = idreceipt;
		this.iditemconcept = iditemconcept;
	}

	public int getIdreceipt() {
		return this.idreceipt;
	}

	public void setIdreceipt(int idreceipt) {
		this.idreceipt = idreceipt;
	}

	public int getIditemconcept() {
		return this.iditemconcept;
	}

	public void setIditemconcept(int iditemconcept) {
		this.iditemconcept = iditemconcept;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemId))
			return false;
		ItemId castOther = (ItemId) other;

		return (this.getIdreceipt() == castOther.getIdreceipt())
				&& (this.getIditemconcept() == castOther.getIditemconcept());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdreceipt();
		result = 37 * result + this.getIditemconcept();
		return result;
	}

}
