package co.com.soinsoftware.billing.entity;

// Generated 26-may-2016 15:17:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Itemconcept generated by hbm2java
 */
public class Itemconcept implements java.io.Serializable {

	private Integer id;
	private Configuration configuration;
	private String name;
	private BigDecimal percentage;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Itemconcept() {
	}

	public Itemconcept(Configuration configuration, String name,
			BigDecimal percentage, Date creation, Date updated, boolean enabled) {
		this.configuration = configuration;
		this.name = name;
		this.percentage = percentage;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Configuration getConfiguration() {
		return this.configuration;
	}

	public void setConfiguration(Configuration configuration) {
		this.configuration = configuration;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
