package co.com.soinsoftware.billing.entity;

// Generated 26-may-2016 15:17:44 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Receipt generated by hbm2java
 */
public class Receipt implements java.io.Serializable {

	private Integer id;
	private Company company;
	private Configuration configuration;
	private User userByIduser;
	private User userByIdcreatoruser;
	private User userByIdlastchangeuser;
	private long number;
	private Date date;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Receipt() {
	}

	public Receipt(Company company, Configuration configuration,
			User userByIduser, User userByIdcreatoruser,
			User userByIdlastchangeuser, long number, Date date, Date creation,
			Date updated, boolean enabled) {
		this.company = company;
		this.configuration = configuration;
		this.userByIduser = userByIduser;
		this.userByIdcreatoruser = userByIdcreatoruser;
		this.userByIdlastchangeuser = userByIdlastchangeuser;
		this.number = number;
		this.date = date;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Configuration getConfiguration() {
		return this.configuration;
	}

	public void setConfiguration(Configuration configuration) {
		this.configuration = configuration;
	}

	public User getUserByIduser() {
		return this.userByIduser;
	}

	public void setUserByIduser(User userByIduser) {
		this.userByIduser = userByIduser;
	}

	public User getUserByIdcreatoruser() {
		return this.userByIdcreatoruser;
	}

	public void setUserByIdcreatoruser(User userByIdcreatoruser) {
		this.userByIdcreatoruser = userByIdcreatoruser;
	}

	public User getUserByIdlastchangeuser() {
		return this.userByIdlastchangeuser;
	}

	public void setUserByIdlastchangeuser(User userByIdlastchangeuser) {
		this.userByIdlastchangeuser = userByIdlastchangeuser;
	}

	public long getNumber() {
		return this.number;
	}

	public void setNumber(long number) {
		this.number = number;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
